package com.example.GreenBascket.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data // @Data includes @NoArgsConstructor and @AllArgsConstructor automatically if you use it.
@NoArgsConstructor
@AllArgsConstructor
public class CartItemRequest {
    private Long productId;
    private BigDecimal quantity; // Changed from int to BigDecimal

    // Getters and Setters are automatically generated by Lombok's @Data
    // If not using Lombok, ensure your manual getters/setters also use BigDecimal
}